package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.C0164t;
import com.google.android.gms.common.api.C0231x;
import com.google.android.gms.common.api.Status;

public class au extends C0164t {
    private final Status f4193a;

    public Integer m7399a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void m7400a(C0231x c0231x) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status m7401b() {
        return this.f4193a;
    }
}
