package android.support.design;

/* renamed from: android.support.design.h */
public final class R {
    public static final int[] ActionBar;
    public static final int[] ActionBarLayout;
    public static final int ActionBarLayout_android_layout_gravity = 0;
    public static final int ActionBar_background = 10;
    public static final int ActionBar_backgroundSplit = 12;
    public static final int ActionBar_backgroundStacked = 11;
    public static final int ActionBar_contentInsetEnd = 21;
    public static final int ActionBar_contentInsetLeft = 22;
    public static final int ActionBar_contentInsetRight = 23;
    public static final int ActionBar_contentInsetStart = 20;
    public static final int ActionBar_customNavigationLayout = 13;
    public static final int ActionBar_displayOptions = 3;
    public static final int ActionBar_divider = 9;
    public static final int ActionBar_elevation = 24;
    public static final int ActionBar_height = 0;
    public static final int ActionBar_hideOnContentScroll = 19;
    public static final int ActionBar_homeAsUpIndicator = 26;
    public static final int ActionBar_homeLayout = 14;
    public static final int ActionBar_icon = 7;
    public static final int ActionBar_indeterminateProgressStyle = 16;
    public static final int ActionBar_itemPadding = 18;
    public static final int ActionBar_logo = 8;
    public static final int ActionBar_navigationMode = 2;
    public static final int ActionBar_popupTheme = 25;
    public static final int ActionBar_progressBarPadding = 17;
    public static final int ActionBar_progressBarStyle = 15;
    public static final int ActionBar_subtitle = 4;
    public static final int ActionBar_subtitleTextStyle = 6;
    public static final int ActionBar_title = 1;
    public static final int ActionBar_titleTextStyle = 5;
    public static final int[] ActionMenuItemView;
    public static final int ActionMenuItemView_android_minWidth = 0;
    public static final int[] ActionMenuView;
    public static final int[] ActionMode;
    public static final int ActionMode_background = 3;
    public static final int ActionMode_backgroundSplit = 4;
    public static final int ActionMode_closeItemLayout = 5;
    public static final int ActionMode_height = 0;
    public static final int ActionMode_subtitleTextStyle = 2;
    public static final int ActionMode_titleTextStyle = 1;
    public static final int[] ActivityChooserView;
    public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
    public static final int ActivityChooserView_initialActivityCount = 0;
    public static final int[] AlertDialog;
    public static final int AlertDialog_android_layout = 0;
    public static final int AlertDialog_buttonPanelSideLayout = 1;
    public static final int AlertDialog_listItemLayout = 5;
    public static final int AlertDialog_listLayout = 2;
    public static final int AlertDialog_multiChoiceItemLayout = 3;
    public static final int AlertDialog_singleChoiceItemLayout = 4;
    public static final int[] AppBarLayout;
    public static final int[] AppBarLayout_LayoutParams;
    public static final int AppBarLayout_LayoutParams_layout_scrollFlags = 0;
    public static final int AppBarLayout_LayoutParams_layout_scrollInterpolator = 1;
    public static final int AppBarLayout_android_background = 0;
    public static final int AppBarLayout_elevation = 1;
    public static final int AppBarLayout_expanded = 2;
    public static final int[] AppCompatImageView;
    public static final int AppCompatImageView_android_src = 0;
    public static final int AppCompatImageView_srcCompat = 1;
    public static final int[] AppCompatTextView;
    public static final int AppCompatTextView_android_textAppearance = 0;
    public static final int AppCompatTextView_textAllCaps = 1;
    public static final int[] AppCompatTheme;
    public static final int AppCompatTheme_actionBarDivider = 23;
    public static final int AppCompatTheme_actionBarItemBackground = 24;
    public static final int AppCompatTheme_actionBarPopupTheme = 17;
    public static final int AppCompatTheme_actionBarSize = 22;
    public static final int AppCompatTheme_actionBarSplitStyle = 19;
    public static final int AppCompatTheme_actionBarStyle = 18;
    public static final int AppCompatTheme_actionBarTabBarStyle = 13;
    public static final int AppCompatTheme_actionBarTabStyle = 12;
    public static final int AppCompatTheme_actionBarTabTextStyle = 14;
    public static final int AppCompatTheme_actionBarTheme = 20;
    public static final int AppCompatTheme_actionBarWidgetTheme = 21;
    public static final int AppCompatTheme_actionButtonStyle = 49;
    public static final int AppCompatTheme_actionDropDownStyle = 45;
    public static final int AppCompatTheme_actionMenuTextAppearance = 25;
    public static final int AppCompatTheme_actionMenuTextColor = 26;
    public static final int AppCompatTheme_actionModeBackground = 29;
    public static final int AppCompatTheme_actionModeCloseButtonStyle = 28;
    public static final int AppCompatTheme_actionModeCloseDrawable = 31;
    public static final int AppCompatTheme_actionModeCopyDrawable = 33;
    public static final int AppCompatTheme_actionModeCutDrawable = 32;
    public static final int AppCompatTheme_actionModeFindDrawable = 37;
    public static final int AppCompatTheme_actionModePasteDrawable = 34;
    public static final int AppCompatTheme_actionModePopupWindowStyle = 39;
    public static final int AppCompatTheme_actionModeSelectAllDrawable = 35;
    public static final int AppCompatTheme_actionModeShareDrawable = 36;
    public static final int AppCompatTheme_actionModeSplitBackground = 30;
    public static final int AppCompatTheme_actionModeStyle = 27;
    public static final int AppCompatTheme_actionModeWebSearchDrawable = 38;
    public static final int AppCompatTheme_actionOverflowButtonStyle = 15;
    public static final int AppCompatTheme_actionOverflowMenuStyle = 16;
    public static final int AppCompatTheme_activityChooserViewStyle = 57;
    public static final int AppCompatTheme_alertDialogButtonGroupStyle = 92;
    public static final int AppCompatTheme_alertDialogCenterButtons = 93;
    public static final int AppCompatTheme_alertDialogStyle = 91;
    public static final int AppCompatTheme_alertDialogTheme = 94;
    public static final int AppCompatTheme_android_windowAnimationStyle = 1;
    public static final int AppCompatTheme_android_windowIsFloating = 0;
    public static final int AppCompatTheme_autoCompleteTextViewStyle = 99;
    public static final int AppCompatTheme_borderlessButtonStyle = 54;
    public static final int AppCompatTheme_buttonBarButtonStyle = 51;
    public static final int AppCompatTheme_buttonBarNegativeButtonStyle = 97;
    public static final int AppCompatTheme_buttonBarNeutralButtonStyle = 98;
    public static final int AppCompatTheme_buttonBarPositiveButtonStyle = 96;
    public static final int AppCompatTheme_buttonBarStyle = 50;
    public static final int AppCompatTheme_buttonStyle = 100;
    public static final int AppCompatTheme_buttonStyleSmall = 101;
    public static final int AppCompatTheme_checkboxStyle = 102;
    public static final int AppCompatTheme_checkedTextViewStyle = 103;
    public static final int AppCompatTheme_colorAccent = 84;
    public static final int AppCompatTheme_colorButtonNormal = 88;
    public static final int AppCompatTheme_colorControlActivated = 86;
    public static final int AppCompatTheme_colorControlHighlight = 87;
    public static final int AppCompatTheme_colorControlNormal = 85;
    public static final int AppCompatTheme_colorPrimary = 82;
    public static final int AppCompatTheme_colorPrimaryDark = 83;
    public static final int AppCompatTheme_colorSwitchThumbNormal = 89;
    public static final int AppCompatTheme_controlBackground = 90;
    public static final int AppCompatTheme_dialogPreferredPadding = 43;
    public static final int AppCompatTheme_dialogTheme = 42;
    public static final int AppCompatTheme_dividerHorizontal = 56;
    public static final int AppCompatTheme_dividerVertical = 55;
    public static final int AppCompatTheme_dropDownListViewStyle = 74;
    public static final int AppCompatTheme_dropdownListPreferredItemHeight = 46;
    public static final int AppCompatTheme_editTextBackground = 63;
    public static final int AppCompatTheme_editTextColor = 62;
    public static final int AppCompatTheme_editTextStyle = 104;
    public static final int AppCompatTheme_homeAsUpIndicator = 48;
    public static final int AppCompatTheme_imageButtonStyle = 64;
    public static final int AppCompatTheme_listChoiceBackgroundIndicator = 81;
    public static final int AppCompatTheme_listDividerAlertDialog = 44;
    public static final int AppCompatTheme_listPopupWindowStyle = 75;
    public static final int AppCompatTheme_listPreferredItemHeight = 69;
    public static final int AppCompatTheme_listPreferredItemHeightLarge = 71;
    public static final int AppCompatTheme_listPreferredItemHeightSmall = 70;
    public static final int AppCompatTheme_listPreferredItemPaddingLeft = 72;
    public static final int AppCompatTheme_listPreferredItemPaddingRight = 73;
    public static final int AppCompatTheme_panelBackground = 78;
    public static final int AppCompatTheme_panelMenuListTheme = 80;
    public static final int AppCompatTheme_panelMenuListWidth = 79;
    public static final int AppCompatTheme_popupMenuStyle = 60;
    public static final int AppCompatTheme_popupWindowStyle = 61;
    public static final int AppCompatTheme_radioButtonStyle = 105;
    public static final int AppCompatTheme_ratingBarStyle = 106;
    public static final int AppCompatTheme_ratingBarStyleIndicator = 107;
    public static final int AppCompatTheme_ratingBarStyleSmall = 108;
    public static final int AppCompatTheme_searchViewStyle = 68;
    public static final int AppCompatTheme_seekBarStyle = 109;
    public static final int AppCompatTheme_selectableItemBackground = 52;
    public static final int AppCompatTheme_selectableItemBackgroundBorderless = 53;
    public static final int AppCompatTheme_spinnerDropDownItemStyle = 47;
    public static final int AppCompatTheme_spinnerStyle = 110;
    public static final int AppCompatTheme_switchStyle = 111;
    public static final int AppCompatTheme_textAppearanceLargePopupMenu = 40;
    public static final int AppCompatTheme_textAppearanceListItem = 76;
    public static final int AppCompatTheme_textAppearanceListItemSmall = 77;
    public static final int AppCompatTheme_textAppearanceSearchResultSubtitle = 66;
    public static final int AppCompatTheme_textAppearanceSearchResultTitle = 65;
    public static final int AppCompatTheme_textAppearanceSmallPopupMenu = 41;
    public static final int AppCompatTheme_textColorAlertDialogListItem = 95;
    public static final int AppCompatTheme_textColorSearchUrl = 67;
    public static final int AppCompatTheme_toolbarNavigationButtonStyle = 59;
    public static final int AppCompatTheme_toolbarStyle = 58;
    public static final int AppCompatTheme_windowActionBar = 2;
    public static final int AppCompatTheme_windowActionBarOverlay = 4;
    public static final int AppCompatTheme_windowActionModeOverlay = 5;
    public static final int AppCompatTheme_windowFixedHeightMajor = 9;
    public static final int AppCompatTheme_windowFixedHeightMinor = 7;
    public static final int AppCompatTheme_windowFixedWidthMajor = 6;
    public static final int AppCompatTheme_windowFixedWidthMinor = 8;
    public static final int AppCompatTheme_windowMinWidthMajor = 10;
    public static final int AppCompatTheme_windowMinWidthMinor = 11;
    public static final int AppCompatTheme_windowNoTitle = 3;
    public static final int[] BottomSheetBehavior_Params;
    public static final int BottomSheetBehavior_Params_behavior_hideable = 1;
    public static final int BottomSheetBehavior_Params_behavior_peekHeight = 0;
    public static final int[] ButtonBarLayout;
    public static final int ButtonBarLayout_allowStacking = 0;
    public static final int[] CollapsingAppBarLayout_LayoutParams;
    public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseMode = 0;
    public static final int f89xad49a364 = 1;
    public static final int[] CollapsingToolbarLayout;
    public static final int CollapsingToolbarLayout_collapsedTitleGravity = 11;
    public static final int CollapsingToolbarLayout_collapsedTitleTextAppearance = 7;
    public static final int CollapsingToolbarLayout_contentScrim = 8;
    public static final int CollapsingToolbarLayout_expandedTitleGravity = 12;
    public static final int CollapsingToolbarLayout_expandedTitleMargin = 1;
    public static final int CollapsingToolbarLayout_expandedTitleMarginBottom = 5;
    public static final int CollapsingToolbarLayout_expandedTitleMarginEnd = 4;
    public static final int CollapsingToolbarLayout_expandedTitleMarginStart = 2;
    public static final int CollapsingToolbarLayout_expandedTitleMarginTop = 3;
    public static final int CollapsingToolbarLayout_expandedTitleTextAppearance = 6;
    public static final int CollapsingToolbarLayout_statusBarScrim = 9;
    public static final int CollapsingToolbarLayout_title = 0;
    public static final int CollapsingToolbarLayout_titleEnabled = 13;
    public static final int CollapsingToolbarLayout_toolbarId = 10;
    public static final int[] CompoundButton;
    public static final int CompoundButton_android_button = 0;
    public static final int CompoundButton_buttonTint = 1;
    public static final int CompoundButton_buttonTintMode = 2;
    public static final int[] CoordinatorLayout;
    public static final int[] CoordinatorLayout_LayoutParams;
    public static final int CoordinatorLayout_LayoutParams_android_layout_gravity = 0;
    public static final int CoordinatorLayout_LayoutParams_layout_anchor = 2;
    public static final int CoordinatorLayout_LayoutParams_layout_anchorGravity = 4;
    public static final int CoordinatorLayout_LayoutParams_layout_behavior = 1;
    public static final int CoordinatorLayout_LayoutParams_layout_keyline = 3;
    public static final int CoordinatorLayout_keylines = 0;
    public static final int CoordinatorLayout_statusBarBackground = 1;
    public static final int[] DesignTheme;
    public static final int DesignTheme_bottomSheetDialogTheme = 0;
    public static final int DesignTheme_bottomSheetStyle = 1;
    public static final int DesignTheme_textColorError = 2;
    public static final int[] DrawerArrowToggle;
    public static final int DrawerArrowToggle_arrowHeadLength = 4;
    public static final int DrawerArrowToggle_arrowShaftLength = 5;
    public static final int DrawerArrowToggle_barLength = 6;
    public static final int DrawerArrowToggle_color = 0;
    public static final int DrawerArrowToggle_drawableSize = 2;
    public static final int DrawerArrowToggle_gapBetweenBars = 3;
    public static final int DrawerArrowToggle_spinBars = 1;
    public static final int DrawerArrowToggle_thickness = 7;
    public static final int[] FloatingActionButton;
    public static final int FloatingActionButton_backgroundTint = 6;
    public static final int FloatingActionButton_backgroundTintMode = 7;
    public static final int FloatingActionButton_borderWidth = 4;
    public static final int FloatingActionButton_elevation = 0;
    public static final int FloatingActionButton_fabSize = 2;
    public static final int FloatingActionButton_pressedTranslationZ = 3;
    public static final int FloatingActionButton_rippleColor = 1;
    public static final int FloatingActionButton_useCompatPadding = 5;
    public static final int[] ForegroundLinearLayout;
    public static final int ForegroundLinearLayout_android_foreground = 0;
    public static final int ForegroundLinearLayout_android_foregroundGravity = 1;
    public static final int ForegroundLinearLayout_foregroundInsidePadding = 2;
    public static final int[] LinearLayoutCompat;
    public static final int[] LinearLayoutCompat_Layout;
    public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
    public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
    public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
    public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
    public static final int LinearLayoutCompat_android_baselineAligned = 2;
    public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
    public static final int LinearLayoutCompat_android_gravity = 0;
    public static final int LinearLayoutCompat_android_orientation = 1;
    public static final int LinearLayoutCompat_android_weightSum = 4;
    public static final int LinearLayoutCompat_divider = 5;
    public static final int LinearLayoutCompat_dividerPadding = 8;
    public static final int LinearLayoutCompat_measureWithLargestChild = 6;
    public static final int LinearLayoutCompat_showDividers = 7;
    public static final int[] ListPopupWindow;
    public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
    public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
    public static final int[] MenuGroup;
    public static final int MenuGroup_android_checkableBehavior = 5;
    public static final int MenuGroup_android_enabled = 0;
    public static final int MenuGroup_android_id = 1;
    public static final int MenuGroup_android_menuCategory = 3;
    public static final int MenuGroup_android_orderInCategory = 4;
    public static final int MenuGroup_android_visible = 2;
    public static final int[] MenuItem;
    public static final int MenuItem_actionLayout = 14;
    public static final int MenuItem_actionProviderClass = 16;
    public static final int MenuItem_actionViewClass = 15;
    public static final int MenuItem_android_alphabeticShortcut = 9;
    public static final int MenuItem_android_checkable = 11;
    public static final int MenuItem_android_checked = 3;
    public static final int MenuItem_android_enabled = 1;
    public static final int MenuItem_android_icon = 0;
    public static final int MenuItem_android_id = 2;
    public static final int MenuItem_android_menuCategory = 5;
    public static final int MenuItem_android_numericShortcut = 10;
    public static final int MenuItem_android_onClick = 12;
    public static final int MenuItem_android_orderInCategory = 6;
    public static final int MenuItem_android_title = 7;
    public static final int MenuItem_android_titleCondensed = 8;
    public static final int MenuItem_android_visible = 4;
    public static final int MenuItem_showAsAction = 13;
    public static final int[] MenuView;
    public static final int MenuView_android_headerBackground = 4;
    public static final int MenuView_android_horizontalDivider = 2;
    public static final int MenuView_android_itemBackground = 5;
    public static final int MenuView_android_itemIconDisabledAlpha = 6;
    public static final int MenuView_android_itemTextAppearance = 1;
    public static final int MenuView_android_verticalDivider = 3;
    public static final int MenuView_android_windowAnimationStyle = 0;
    public static final int MenuView_preserveIconSpacing = 7;
    public static final int[] NavigationView;
    public static final int NavigationView_android_background = 0;
    public static final int NavigationView_android_fitsSystemWindows = 1;
    public static final int NavigationView_android_maxWidth = 2;
    public static final int NavigationView_elevation = 3;
    public static final int NavigationView_headerLayout = 9;
    public static final int NavigationView_itemBackground = 7;
    public static final int NavigationView_itemIconTint = 5;
    public static final int NavigationView_itemTextAppearance = 8;
    public static final int NavigationView_itemTextColor = 6;
    public static final int NavigationView_menu = 4;
    public static final int[] PopupWindow;
    public static final int[] PopupWindowBackgroundState;
    public static final int PopupWindowBackgroundState_state_above_anchor = 0;
    public static final int PopupWindow_android_popupBackground = 0;
    public static final int PopupWindow_overlapAnchor = 1;
    public static final int[] RecyclerView;
    public static final int RecyclerView_android_orientation = 0;
    public static final int RecyclerView_layoutManager = 1;
    public static final int RecyclerView_reverseLayout = 3;
    public static final int RecyclerView_spanCount = 2;
    public static final int RecyclerView_stackFromEnd = 4;
    public static final int[] ScrimInsetsFrameLayout;
    public static final int ScrimInsetsFrameLayout_insetForeground = 0;
    public static final int[] ScrollingViewBehavior_Params;
    public static final int ScrollingViewBehavior_Params_behavior_overlapTop = 0;
    public static final int[] SearchView;
    public static final int SearchView_android_focusable = 0;
    public static final int SearchView_android_imeOptions = 3;
    public static final int SearchView_android_inputType = 2;
    public static final int SearchView_android_maxWidth = 1;
    public static final int SearchView_closeIcon = 8;
    public static final int SearchView_commitIcon = 13;
    public static final int SearchView_defaultQueryHint = 7;
    public static final int SearchView_goIcon = 9;
    public static final int SearchView_iconifiedByDefault = 5;
    public static final int SearchView_layout = 4;
    public static final int SearchView_queryBackground = 15;
    public static final int SearchView_queryHint = 6;
    public static final int SearchView_searchHintIcon = 11;
    public static final int SearchView_searchIcon = 10;
    public static final int SearchView_submitBackground = 16;
    public static final int SearchView_suggestionRowLayout = 14;
    public static final int SearchView_voiceIcon = 12;
    public static final int[] SnackbarLayout;
    public static final int SnackbarLayout_android_maxWidth = 0;
    public static final int SnackbarLayout_elevation = 1;
    public static final int SnackbarLayout_maxActionInlineWidth = 2;
    public static final int[] Spinner;
    public static final int Spinner_android_dropDownWidth = 3;
    public static final int Spinner_android_entries = 0;
    public static final int Spinner_android_popupBackground = 1;
    public static final int Spinner_android_prompt = 2;
    public static final int Spinner_popupTheme = 4;
    public static final int[] SwitchCompat;
    public static final int SwitchCompat_android_textOff = 1;
    public static final int SwitchCompat_android_textOn = 0;
    public static final int SwitchCompat_android_thumb = 2;
    public static final int SwitchCompat_showText = 9;
    public static final int SwitchCompat_splitTrack = 8;
    public static final int SwitchCompat_switchMinWidth = 6;
    public static final int SwitchCompat_switchPadding = 7;
    public static final int SwitchCompat_switchTextAppearance = 5;
    public static final int SwitchCompat_thumbTextPadding = 4;
    public static final int SwitchCompat_track = 3;
    public static final int[] TabItem;
    public static final int TabItem_android_icon = 0;
    public static final int TabItem_android_layout = 1;
    public static final int TabItem_android_text = 2;
    public static final int[] TabLayout;
    public static final int TabLayout_tabBackground = 3;
    public static final int TabLayout_tabContentStart = 2;
    public static final int TabLayout_tabGravity = 5;
    public static final int TabLayout_tabIndicatorColor = 0;
    public static final int TabLayout_tabIndicatorHeight = 1;
    public static final int TabLayout_tabMaxWidth = 7;
    public static final int TabLayout_tabMinWidth = 6;
    public static final int TabLayout_tabMode = 4;
    public static final int TabLayout_tabPadding = 15;
    public static final int TabLayout_tabPaddingBottom = 14;
    public static final int TabLayout_tabPaddingEnd = 13;
    public static final int TabLayout_tabPaddingStart = 11;
    public static final int TabLayout_tabPaddingTop = 12;
    public static final int TabLayout_tabSelectedTextColor = 10;
    public static final int TabLayout_tabTextAppearance = 8;
    public static final int TabLayout_tabTextColor = 9;
    public static final int[] TextAppearance;
    public static final int TextAppearance_android_shadowColor = 4;
    public static final int TextAppearance_android_shadowDx = 5;
    public static final int TextAppearance_android_shadowDy = 6;
    public static final int TextAppearance_android_shadowRadius = 7;
    public static final int TextAppearance_android_textColor = 3;
    public static final int TextAppearance_android_textSize = 0;
    public static final int TextAppearance_android_textStyle = 2;
    public static final int TextAppearance_android_typeface = 1;
    public static final int TextAppearance_textAllCaps = 8;
    public static final int[] TextInputLayout;
    public static final int TextInputLayout_android_hint = 1;
    public static final int TextInputLayout_android_textColorHint = 0;
    public static final int TextInputLayout_counterEnabled = 6;
    public static final int TextInputLayout_counterMaxLength = 7;
    public static final int TextInputLayout_counterOverflowTextAppearance = 9;
    public static final int TextInputLayout_counterTextAppearance = 8;
    public static final int TextInputLayout_errorEnabled = 4;
    public static final int TextInputLayout_errorTextAppearance = 5;
    public static final int TextInputLayout_hintAnimationEnabled = 10;
    public static final int TextInputLayout_hintEnabled = 3;
    public static final int TextInputLayout_hintTextAppearance = 2;
    public static final int[] Toolbar;
    public static final int Toolbar_android_gravity = 0;
    public static final int Toolbar_android_minHeight = 1;
    public static final int Toolbar_collapseContentDescription = 19;
    public static final int Toolbar_collapseIcon = 18;
    public static final int Toolbar_contentInsetEnd = 6;
    public static final int Toolbar_contentInsetLeft = 7;
    public static final int Toolbar_contentInsetRight = 8;
    public static final int Toolbar_contentInsetStart = 5;
    public static final int Toolbar_logo = 4;
    public static final int Toolbar_logoDescription = 22;
    public static final int Toolbar_maxButtonHeight = 17;
    public static final int Toolbar_navigationContentDescription = 21;
    public static final int Toolbar_navigationIcon = 20;
    public static final int Toolbar_popupTheme = 9;
    public static final int Toolbar_subtitle = 3;
    public static final int Toolbar_subtitleTextAppearance = 11;
    public static final int Toolbar_subtitleTextColor = 24;
    public static final int Toolbar_title = 2;
    public static final int Toolbar_titleMarginBottom = 16;
    public static final int Toolbar_titleMarginEnd = 14;
    public static final int Toolbar_titleMarginStart = 13;
    public static final int Toolbar_titleMarginTop = 15;
    public static final int Toolbar_titleMargins = 12;
    public static final int Toolbar_titleTextAppearance = 10;
    public static final int Toolbar_titleTextColor = 23;
    public static final int[] View;
    public static final int[] ViewBackgroundHelper;
    public static final int ViewBackgroundHelper_android_background = 0;
    public static final int ViewBackgroundHelper_backgroundTint = 1;
    public static final int ViewBackgroundHelper_backgroundTintMode = 2;
    public static final int[] ViewStubCompat;
    public static final int ViewStubCompat_android_id = 0;
    public static final int ViewStubCompat_android_inflatedId = 2;
    public static final int ViewStubCompat_android_layout = 1;
    public static final int View_android_focusable = 1;
    public static final int View_android_theme = 0;
    public static final int View_paddingEnd = 3;
    public static final int View_paddingStart = 2;
    public static final int View_theme = 4;

    static {
        ActionBar = new int[]{android.support.v7.p018b.R.height, android.support.v7.p018b.R.title, android.support.v7.p018b.R.navigationMode, android.support.v7.p018b.R.displayOptions, android.support.v7.p018b.R.subtitle, android.support.v7.p018b.R.titleTextStyle, android.support.v7.p018b.R.subtitleTextStyle, android.support.v7.p018b.R.icon, android.support.v7.p018b.R.logo, android.support.v7.p018b.R.divider, android.support.v7.p018b.R.background, android.support.v7.p018b.R.backgroundStacked, android.support.v7.p018b.R.backgroundSplit, android.support.v7.p018b.R.customNavigationLayout, android.support.v7.p018b.R.homeLayout, android.support.v7.p018b.R.progressBarStyle, android.support.v7.p018b.R.indeterminateProgressStyle, android.support.v7.p018b.R.progressBarPadding, android.support.v7.p018b.R.itemPadding, android.support.v7.p018b.R.hideOnContentScroll, android.support.v7.p018b.R.contentInsetStart, android.support.v7.p018b.R.contentInsetEnd, android.support.v7.p018b.R.contentInsetLeft, android.support.v7.p018b.R.contentInsetRight, android.support.v7.p018b.R.elevation, android.support.v7.p018b.R.popupTheme, android.support.v7.p018b.R.homeAsUpIndicator};
        int[] iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16842931;
        ActionBarLayout = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = 16843071;
        ActionMenuItemView = iArr;
        ActionMenuView = new int[View_android_theme];
        ActionMode = new int[]{android.support.v7.p018b.R.height, android.support.v7.p018b.R.titleTextStyle, android.support.v7.p018b.R.subtitleTextStyle, android.support.v7.p018b.R.background, android.support.v7.p018b.R.backgroundSplit, android.support.v7.p018b.R.closeItemLayout};
        ActivityChooserView = new int[]{android.support.v7.p018b.R.initialActivityCount, android.support.v7.p018b.R.expandActivityOverflowButtonDrawable};
        AlertDialog = new int[]{16842994, android.support.v7.p018b.R.buttonPanelSideLayout, android.support.v7.p018b.R.listLayout, android.support.v7.p018b.R.multiChoiceItemLayout, android.support.v7.p018b.R.singleChoiceItemLayout, android.support.v7.p018b.R.listItemLayout};
        AppBarLayout = new int[]{16842964, android.support.v7.p018b.R.elevation, R.expanded};
        AppBarLayout_LayoutParams = new int[]{R.layout_scrollFlags, R.layout_scrollInterpolator};
        AppCompatImageView = new int[]{16843033, android.support.v7.p018b.R.srcCompat};
        AppCompatTextView = new int[]{16842804, android.support.v7.p018b.R.textAllCaps};
        AppCompatTheme = new int[]{16842839, 16842926, android.support.v7.p018b.R.windowActionBar, android.support.v7.p018b.R.windowNoTitle, android.support.v7.p018b.R.windowActionBarOverlay, android.support.v7.p018b.R.windowActionModeOverlay, android.support.v7.p018b.R.windowFixedWidthMajor, android.support.v7.p018b.R.windowFixedHeightMinor, android.support.v7.p018b.R.windowFixedWidthMinor, android.support.v7.p018b.R.windowFixedHeightMajor, android.support.v7.p018b.R.windowMinWidthMajor, android.support.v7.p018b.R.windowMinWidthMinor, android.support.v7.p018b.R.actionBarTabStyle, android.support.v7.p018b.R.actionBarTabBarStyle, android.support.v7.p018b.R.actionBarTabTextStyle, android.support.v7.p018b.R.actionOverflowButtonStyle, android.support.v7.p018b.R.actionOverflowMenuStyle, android.support.v7.p018b.R.actionBarPopupTheme, android.support.v7.p018b.R.actionBarStyle, android.support.v7.p018b.R.actionBarSplitStyle, android.support.v7.p018b.R.actionBarTheme, android.support.v7.p018b.R.actionBarWidgetTheme, android.support.v7.p018b.R.actionBarSize, android.support.v7.p018b.R.actionBarDivider, android.support.v7.p018b.R.actionBarItemBackground, android.support.v7.p018b.R.actionMenuTextAppearance, android.support.v7.p018b.R.actionMenuTextColor, android.support.v7.p018b.R.actionModeStyle, android.support.v7.p018b.R.actionModeCloseButtonStyle, android.support.v7.p018b.R.actionModeBackground, android.support.v7.p018b.R.actionModeSplitBackground, android.support.v7.p018b.R.actionModeCloseDrawable, android.support.v7.p018b.R.actionModeCutDrawable, android.support.v7.p018b.R.actionModeCopyDrawable, android.support.v7.p018b.R.actionModePasteDrawable, android.support.v7.p018b.R.actionModeSelectAllDrawable, android.support.v7.p018b.R.actionModeShareDrawable, android.support.v7.p018b.R.actionModeFindDrawable, android.support.v7.p018b.R.actionModeWebSearchDrawable, android.support.v7.p018b.R.actionModePopupWindowStyle, android.support.v7.p018b.R.textAppearanceLargePopupMenu, android.support.v7.p018b.R.textAppearanceSmallPopupMenu, android.support.v7.p018b.R.dialogTheme, android.support.v7.p018b.R.dialogPreferredPadding, android.support.v7.p018b.R.listDividerAlertDialog, android.support.v7.p018b.R.actionDropDownStyle, android.support.v7.p018b.R.dropdownListPreferredItemHeight, android.support.v7.p018b.R.spinnerDropDownItemStyle, android.support.v7.p018b.R.homeAsUpIndicator, android.support.v7.p018b.R.actionButtonStyle, android.support.v7.p018b.R.buttonBarStyle, android.support.v7.p018b.R.buttonBarButtonStyle, android.support.v7.p018b.R.selectableItemBackground, android.support.v7.p018b.R.selectableItemBackgroundBorderless, android.support.v7.p018b.R.borderlessButtonStyle, android.support.v7.p018b.R.dividerVertical, android.support.v7.p018b.R.dividerHorizontal, android.support.v7.p018b.R.activityChooserViewStyle, android.support.v7.p018b.R.toolbarStyle, android.support.v7.p018b.R.toolbarNavigationButtonStyle, android.support.v7.p018b.R.popupMenuStyle, android.support.v7.p018b.R.popupWindowStyle, android.support.v7.p018b.R.editTextColor, android.support.v7.p018b.R.editTextBackground, android.support.v7.p018b.R.imageButtonStyle, android.support.v7.p018b.R.textAppearanceSearchResultTitle, android.support.v7.p018b.R.textAppearanceSearchResultSubtitle, android.support.v7.p018b.R.textColorSearchUrl, android.support.v7.p018b.R.searchViewStyle, android.support.v7.p018b.R.listPreferredItemHeight, android.support.v7.p018b.R.listPreferredItemHeightSmall, android.support.v7.p018b.R.listPreferredItemHeightLarge, android.support.v7.p018b.R.listPreferredItemPaddingLeft, android.support.v7.p018b.R.listPreferredItemPaddingRight, android.support.v7.p018b.R.dropDownListViewStyle, android.support.v7.p018b.R.listPopupWindowStyle, android.support.v7.p018b.R.textAppearanceListItem, android.support.v7.p018b.R.textAppearanceListItemSmall, android.support.v7.p018b.R.panelBackground, android.support.v7.p018b.R.panelMenuListWidth, android.support.v7.p018b.R.panelMenuListTheme, android.support.v7.p018b.R.listChoiceBackgroundIndicator, android.support.v7.p018b.R.colorPrimary, android.support.v7.p018b.R.colorPrimaryDark, android.support.v7.p018b.R.colorAccent, android.support.v7.p018b.R.colorControlNormal, android.support.v7.p018b.R.colorControlActivated, android.support.v7.p018b.R.colorControlHighlight, android.support.v7.p018b.R.colorButtonNormal, android.support.v7.p018b.R.colorSwitchThumbNormal, android.support.v7.p018b.R.controlBackground, android.support.v7.p018b.R.alertDialogStyle, android.support.v7.p018b.R.alertDialogButtonGroupStyle, android.support.v7.p018b.R.alertDialogCenterButtons, android.support.v7.p018b.R.alertDialogTheme, android.support.v7.p018b.R.textColorAlertDialogListItem, android.support.v7.p018b.R.buttonBarPositiveButtonStyle, android.support.v7.p018b.R.buttonBarNegativeButtonStyle, android.support.v7.p018b.R.buttonBarNeutralButtonStyle, android.support.v7.p018b.R.autoCompleteTextViewStyle, android.support.v7.p018b.R.buttonStyle, android.support.v7.p018b.R.buttonStyleSmall, android.support.v7.p018b.R.checkboxStyle, android.support.v7.p018b.R.checkedTextViewStyle, android.support.v7.p018b.R.editTextStyle, android.support.v7.p018b.R.radioButtonStyle, android.support.v7.p018b.R.ratingBarStyle, android.support.v7.p018b.R.ratingBarStyleIndicator, android.support.v7.p018b.R.ratingBarStyleSmall, android.support.v7.p018b.R.seekBarStyle, android.support.v7.p018b.R.spinnerStyle, android.support.v7.p018b.R.switchStyle};
        BottomSheetBehavior_Params = new int[]{R.behavior_peekHeight, R.behavior_hideable};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = android.support.v7.p018b.R.allowStacking;
        ButtonBarLayout = iArr;
        CollapsingAppBarLayout_LayoutParams = new int[]{R.layout_collapseMode, R.layout_collapseParallaxMultiplier};
        CollapsingToolbarLayout = new int[]{android.support.v7.p018b.R.title, R.expandedTitleMargin, R.expandedTitleMarginStart, R.expandedTitleMarginTop, R.expandedTitleMarginEnd, R.expandedTitleMarginBottom, R.expandedTitleTextAppearance, R.collapsedTitleTextAppearance, R.contentScrim, R.statusBarScrim, R.toolbarId, R.collapsedTitleGravity, R.expandedTitleGravity, R.titleEnabled};
        CompoundButton = new int[]{16843015, android.support.v7.p018b.R.buttonTint, android.support.v7.p018b.R.buttonTintMode};
        CoordinatorLayout = new int[]{R.keylines, R.statusBarBackground};
        CoordinatorLayout_LayoutParams = new int[]{16842931, R.layout_behavior, R.layout_anchor, R.layout_keyline, R.layout_anchorGravity};
        DesignTheme = new int[]{R.bottomSheetDialogTheme, R.bottomSheetStyle, R.textColorError};
        DrawerArrowToggle = new int[]{android.support.v7.p018b.R.color, android.support.v7.p018b.R.spinBars, android.support.v7.p018b.R.drawableSize, android.support.v7.p018b.R.gapBetweenBars, android.support.v7.p018b.R.arrowHeadLength, android.support.v7.p018b.R.arrowShaftLength, android.support.v7.p018b.R.barLength, android.support.v7.p018b.R.thickness};
        FloatingActionButton = new int[]{android.support.v7.p018b.R.elevation, R.rippleColor, R.fabSize, R.pressedTranslationZ, R.borderWidth, R.useCompatPadding, android.support.v7.p018b.R.backgroundTint, android.support.v7.p018b.R.backgroundTintMode};
        ForegroundLinearLayout = new int[]{16843017, 16843264, R.foregroundInsidePadding};
        LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, android.support.v7.p018b.R.divider, android.support.v7.p018b.R.measureWithLargestChild, android.support.v7.p018b.R.showDividers, android.support.v7.p018b.R.dividerPadding};
        LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
        ListPopupWindow = new int[]{16843436, 16843437};
        MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
        MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, android.support.v7.p018b.R.showAsAction, android.support.v7.p018b.R.actionLayout, android.support.v7.p018b.R.actionViewClass, android.support.v7.p018b.R.actionProviderClass};
        MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, android.support.v7.p018b.R.preserveIconSpacing};
        NavigationView = new int[]{16842964, 16842973, 16843039, android.support.v7.p018b.R.elevation, R.menu, R.itemIconTint, R.itemTextColor, R.itemBackground, R.itemTextAppearance, R.headerLayout};
        PopupWindow = new int[]{16843126, android.support.v7.p018b.R.overlapAnchor};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = android.support.v7.p018b.R.state_above_anchor;
        PopupWindowBackgroundState = iArr;
        RecyclerView = new int[]{16842948, R.layoutManager, R.spanCount, R.reverseLayout, R.stackFromEnd};
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = R.insetForeground;
        ScrimInsetsFrameLayout = iArr;
        iArr = new int[View_android_focusable];
        iArr[View_android_theme] = R.behavior_overlapTop;
        ScrollingViewBehavior_Params = iArr;
        SearchView = new int[]{16842970, 16843039, 16843296, 16843364, android.support.v7.p018b.R.layout, android.support.v7.p018b.R.iconifiedByDefault, android.support.v7.p018b.R.queryHint, android.support.v7.p018b.R.defaultQueryHint, android.support.v7.p018b.R.closeIcon, android.support.v7.p018b.R.goIcon, android.support.v7.p018b.R.searchIcon, android.support.v7.p018b.R.searchHintIcon, android.support.v7.p018b.R.voiceIcon, android.support.v7.p018b.R.commitIcon, android.support.v7.p018b.R.suggestionRowLayout, android.support.v7.p018b.R.queryBackground, android.support.v7.p018b.R.submitBackground};
        SnackbarLayout = new int[]{16843039, android.support.v7.p018b.R.elevation, R.maxActionInlineWidth};
        Spinner = new int[]{16842930, 16843126, 16843131, 16843362, android.support.v7.p018b.R.popupTheme};
        SwitchCompat = new int[]{16843044, 16843045, 16843074, android.support.v7.p018b.R.track, android.support.v7.p018b.R.thumbTextPadding, android.support.v7.p018b.R.switchTextAppearance, android.support.v7.p018b.R.switchMinWidth, android.support.v7.p018b.R.switchPadding, android.support.v7.p018b.R.splitTrack, android.support.v7.p018b.R.showText};
        TabItem = new int[]{16842754, 16842994, 16843087};
        TabLayout = new int[]{R.tabIndicatorColor, R.tabIndicatorHeight, R.tabContentStart, R.tabBackground, R.tabMode, R.tabGravity, R.tabMinWidth, R.tabMaxWidth, R.tabTextAppearance, R.tabTextColor, R.tabSelectedTextColor, R.tabPaddingStart, R.tabPaddingTop, R.tabPaddingEnd, R.tabPaddingBottom, R.tabPadding};
        TextAppearance = new int[]{16842901, 16842902, 16842903, 16842904, 16843105, 16843106, 16843107, 16843108, android.support.v7.p018b.R.textAllCaps};
        TextInputLayout = new int[]{16842906, 16843088, R.hintTextAppearance, R.hintEnabled, R.errorEnabled, R.errorTextAppearance, R.counterEnabled, R.counterMaxLength, R.counterTextAppearance, R.counterOverflowTextAppearance, R.hintAnimationEnabled};
        Toolbar = new int[]{16842927, 16843072, android.support.v7.p018b.R.title, android.support.v7.p018b.R.subtitle, android.support.v7.p018b.R.logo, android.support.v7.p018b.R.contentInsetStart, android.support.v7.p018b.R.contentInsetEnd, android.support.v7.p018b.R.contentInsetLeft, android.support.v7.p018b.R.contentInsetRight, android.support.v7.p018b.R.popupTheme, android.support.v7.p018b.R.titleTextAppearance, android.support.v7.p018b.R.subtitleTextAppearance, android.support.v7.p018b.R.titleMargins, android.support.v7.p018b.R.titleMarginStart, android.support.v7.p018b.R.titleMarginEnd, android.support.v7.p018b.R.titleMarginTop, android.support.v7.p018b.R.titleMarginBottom, android.support.v7.p018b.R.maxButtonHeight, android.support.v7.p018b.R.collapseIcon, android.support.v7.p018b.R.collapseContentDescription, android.support.v7.p018b.R.navigationIcon, android.support.v7.p018b.R.navigationContentDescription, android.support.v7.p018b.R.logoDescription, android.support.v7.p018b.R.titleTextColor, android.support.v7.p018b.R.subtitleTextColor};
        View = new int[]{16842752, 16842970, android.support.v7.p018b.R.paddingStart, android.support.v7.p018b.R.paddingEnd, android.support.v7.p018b.R.theme};
        ViewBackgroundHelper = new int[]{16842964, android.support.v7.p018b.R.backgroundTint, android.support.v7.p018b.R.backgroundTintMode};
        ViewStubCompat = new int[]{16842960, 16842994, 16842995};
    }
}
