package com.google.android.gms.p051b;

import com.google.android.gms.ads.internal.C0056g;
import java.util.List;
import java.util.concurrent.TimeUnit;

@fi
/* renamed from: com.google.android.gms.b.an */
public final class an {
    public static final ae f3399A;
    public static final ae f3400B;
    public static final ae f3401C;
    public static final ae f3402D;
    public static final ae f3403E;
    public static final ae f3404F;
    public static final ae f3405G;
    public static final ae f3406H;
    public static final ae f3407I;
    public static final ae f3408J;
    public static final ae f3409K;
    public static final ae f3410L;
    public static final ae f3411M;
    public static final ae f3412N;
    public static final ae f3413O;
    public static final ae f3414P;
    public static final ae f3415Q;
    public static final ae f3416R;
    public static final ae f3417S;
    public static final ae f3418T;
    public static final ae f3419U;
    public static final ae f3420V;
    public static final ae f3421W;
    public static final ae f3422X;
    public static final ae f3423Y;
    public static final ae f3424Z;
    public static final ae f3425a;
    public static final ae aA;
    public static final ae aB;
    public static final ae aC;
    public static final ae aD;
    public static final ae aE;
    public static final ae aF;
    public static final ae aG;
    public static final ae aa;
    public static final ae ab;
    public static final ae ac;
    public static final ae ad;
    public static final ae ae;
    public static final ae af;
    public static final ae ag;
    public static final ae ah;
    public static final ae ai;
    public static final ae aj;
    public static final ae ak;
    public static final ae al;
    public static final ae am;
    public static final ae an;
    public static final ae ao;
    public static final ae ap;
    public static final ae aq;
    public static final ae ar;
    public static final ae as;
    public static final ae at;
    public static final ae au;
    public static final ae av;
    public static final ae aw;
    public static final ae ax;
    public static final ae ay;
    public static final ae az;
    public static final ae f3426b;
    public static final ae f3427c;
    public static final ae f3428d;
    public static final ae f3429e;
    public static final ae f3430f;
    public static final ae f3431g;
    public static final ae f3432h;
    public static final ae f3433i;
    public static final ae f3434j;
    public static final ae f3435k;
    public static final ae f3436l;
    public static final ae f3437m;
    public static final ae f3438n;
    public static final ae f3439o;
    public static final ae f3440p;
    public static final ae f3441q;
    public static final ae f3442r;
    public static final ae f3443s;
    public static final ae f3444t;
    public static final ae f3445u;
    public static final ae f3446v;
    public static final ae f3447w;
    public static final ae f3448x;
    public static final ae f3449y;
    public static final ae f3450z;

    static {
        f3425a = ae.m6084a(0, "gads:sdk_core_experiment_id");
        f3426b = ae.m6088a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        f3427c = ae.m6087a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
        f3428d = ae.m6084a(0, "gads:request_builder:singleton_webview_experiment_id");
        f3429e = ae.m6087a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(false));
        f3430f = ae.m6084a(0, "gads:sdk_use_dynamic_module_experiment_id");
        f3431g = ae.m6087a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
        f3432h = ae.m6087a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
        f3433i = ae.m6087a(0, "gads:block_autoclicks", Boolean.valueOf(false));
        f3434j = ae.m6084a(0, "gads:block_autoclicks_experiment_id");
        f3435k = ae.m6089b(0, "gads:prefetch:experiment_id");
        f3436l = ae.m6084a(0, "gads:spam_app_context:experiment_id");
        f3437m = ae.m6087a(0, "gads:spam_app_context:enabled", Boolean.valueOf(false));
        f3438n = ae.m6084a(0, "gads:video_stream_cache:experiment_id");
        f3439o = ae.m6085a(0, "gads:video_stream_cache:limit_count", 5);
        f3440p = ae.m6085a(0, "gads:video_stream_cache:limit_space", 8388608);
        f3441q = ae.m6085a(0, "gads:video_stream_exo_cache:buffer_size", 8388608);
        f3442r = ae.m6086a(0, "gads:video_stream_cache:limit_time_sec", 300);
        f3443s = ae.m6086a(0, "gads:video_stream_cache:notify_interval_millis", 1000);
        f3444t = ae.m6085a(0, "gads:video_stream_cache:connect_timeout_millis", 10000);
        f3445u = ae.m6087a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
        f3446v = ae.m6088a(0, "gads:video:metric_frame_hash_times", "");
        f3447w = ae.m6086a(0, "gads:video:metric_frame_hash_time_leniency", 500);
        f3448x = ae.m6089b(0, "gads:spam_ad_id_decorator:experiment_id");
        f3449y = ae.m6087a(0, "gads:spam_ad_id_decorator:enabled", Boolean.valueOf(false));
        f3450z = ae.m6089b(0, "gads:looper_for_gms_client:experiment_id");
        f3399A = ae.m6087a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
        f3400B = ae.m6087a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
        f3401C = ae.m6087a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
        f3402D = ae.m6088a(0, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        f3403E = ae.m6088a(0, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        f3404F = ae.m6088a(0, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        f3405G = ae.m6087a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
        f3406H = ae.m6088a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        f3407I = ae.m6087a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
        f3408J = ae.m6087a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
        f3409K = ae.m6085a(0, "gads:content_length_weight", 1);
        f3410L = ae.m6085a(0, "gads:content_age_weight", 1);
        f3411M = ae.m6085a(0, "gads:min_content_len", 11);
        f3412N = ae.m6085a(0, "gads:fingerprint_number", 10);
        f3413O = ae.m6085a(0, "gads:sleep_sec", 10);
        f3414P = ae.m6087a(0, "gad:app_index_enabled", Boolean.valueOf(true));
        f3415Q = ae.m6087a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
        f3416R = ae.m6086a(0, "gads:app_index:timeout_ms", 1000);
        f3417S = ae.m6084a(0, "gads:app_index:experiment_id");
        f3418T = ae.m6084a(0, "gads:kitkat_interstitial_workaround:experiment_id");
        f3419U = ae.m6087a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
        f3420V = ae.m6087a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
        f3421W = ae.m6087a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
        f3422X = ae.m6084a(0, "gads:interstitial_follow_url:experiment_id");
        f3423Y = ae.m6087a(0, "gads:analytics_enabled", Boolean.valueOf(true));
        f3424Z = ae.m6087a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
        aa = ae.m6085a(0, "gads:webview_cache_version", 0);
        ab = ae.m6089b(0, "gads:pan:experiment_id");
        ac = ae.m6088a(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        ad = ae.m6087a(0, "gads:ad_manager_creator:enabled", Boolean.valueOf(true));
        ae = ae.m6087a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
        af = ae.m6088a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        ag = ae.m6085a(1, "gads:interstitial_ad_pool:max_pools", 3);
        ah = ae.m6085a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        ai = ae.m6085a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        aj = ae.m6084a(1, "gads:interstitial_ad_pool:experiment_id");
        ak = ae.m6087a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
        al = ae.m6087a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
        am = ae.m6086a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
        an = ae.m6087a(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
        ao = ae.m6087a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
        ap = ae.m6087a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
        aq = ae.m6087a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
        ar = ae.m6087a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
        as = ae.m6087a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
        at = ae.m6087a(0, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(false));
        au = ae.m6086a(0, "gads:network:cache_prediction_duration_s", 300);
        av = ae.m6087a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
        aw = ae.m6087a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
        ax = ae.m6086a(0, "gads:ad_loader:timeout_ms", 60000);
        ay = ae.m6086a(0, "gads:rendering:timeout_ms", 60000);
        az = ae.m6087a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
        aA = ae.m6087a(0, "gass:enabled", Boolean.valueOf(false));
        aB = ae.m6087a(0, "gass:enable_int_signal", Boolean.valueOf(true));
        aC = ae.m6087a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
        aD = ae.m6087a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
        aE = ae.m6087a(0, "gads:support_screen_shot", Boolean.valueOf(true));
        aF = ae.m6086a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
        aG = ae.m6087a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    }

    public static List m6108a() {
        return C0056g.m5444h().m6102a();
    }
}
